# Title: Concatanate two FragMap outputs
# Purpose: This script concatanates two FragMap outputs and create comparison plots
# Author: Somak Ray
# Contact: s.ray@northeastern.edu
# Date Created:  2024-01-30
# Last Modified: 2024-04-29
# Dependencies: dplyr, Biostrings, scales, stringr, pheatmap
# Data Sources: Data can be found in the /data directory. Ensure data is generated by latest version of "FragMap"
# Usage: Rscript analysis_of_xyz.R [arguments]
# Version: 1.0.0
# License: MIT License
# Acknowledgements:
# Warnings: This script assumes data is cleaned and formatted as per the specifications in FragMap.

# if (!require("BiocManager", quietly = TRUE))
# install.packages("BiocManager")
# BiocManager::install("Biostrings")

library(Biostrings)
library(dplyr)
library(scales)
library(stringr)
library(viridis)
library(tidyverse)
library(reshape2)
library(RColorBrewer)
library(pheatmap)


rm(list = ls())
set.seed(12345)
setwd(
  #"C:\\Users\\SR\\Documents\\LAB_USERS\\ANEW_RULEBASED_FRAGMAP\\COMPARISON_MAP\\ALL_BY_R\\RelAbd_COMP"
  "C:\\Users\\SR\\Documents\\LAB_USERS\\ANEW_RULEBASED_FRAGMAP\\MODIF_COMPARISOn"
) # Home version

req_col = c('ExptName', 'IonType', 'Annotation', 'VariableMod','FixedMod', 'RelativeIntensity')
valid_ions <- c('b', 'y', 'yb')
common_color <- 'gray30'
ctrl_color <- 'blue' # Exclusive to Control
exp_color <- 'red3'  # Exclusive to Experimental/ Treatment

######################### Input Files  #################################
fastaFile <- "A4V.fasta"
control_file <-  "V2Hyper_SOD1A4VCtrl_S1.0_AnnotData.txt"
experimental_file <- "V2Hyper_SOD1A4VOxDn_S1.0_AnnotData.txt"

ctrl_name <- "ctrl"
treat_name <- "oxdn"


sequence_vector <- function(seq_fasta) {
  seqOb <- readAAStringSet(fastaFile, format = "fasta")
  fullseq <- as.character(seqOb, use.names = FALSE)
  seqList <- strsplit(fullseq, split = "")
  #seqVec <- seqList[[1]][-1]# For eliminating Methionine N-Term
  seqVec <- seqList[[1]]
  return(seqVec)
}



read_df <- function(file2read, cols2use) {
  dd_df <- read.table(file2read, header = TRUE, sep = "\t")
  if (!all(cols2use %in% names(dd_df))) {
    stop("Not all fields are present in 'file2read'.")
  }
  dd_df <- dd_df %>%
    filter(IonType %in% valid_ions) %>%
    select(all_of(cols2use))
  
  return(dd_df)
}

add_column2df <- function(input_df, expname, protein_length) {
  input_df <- input_df %>%
    mutate(
      Start = case_when(
        IonType == 'b' ~ 1,
        IonType == 'y' ~ protein_length - as.integer(str_sub(Annotation, 2)) + 1,
        IonType == 'yb' ~ as.integer(str_split(Annotation, "_", simplify = TRUE)[, 1]),
        TRUE ~ NA_integer_
      ),
      End = case_when(
        IonType == 'b' ~ as.integer(str_sub(Annotation, 2)),
        IonType == 'y' ~ protein_length,
        IonType == 'yb' ~ as.integer(str_split(Annotation, "_", simplify = TRUE)[, 2]),
        TRUE ~ NA_integer_
      )
    ) %>%
    mutate(Height = End - Start + 1) %>% #Height == Length
    mutate(Cond = expname)
  return(input_df)
}


add_termpos2df <- function(input_df, protein_length) {
  input_df <- input_df %>%
    mutate(
      Start = case_when(
        IonType == 'b' ~ 1,
        IonType == 'y' ~ protein_length - as.integer(str_sub(Annotation, 2)) + 1,
        IonType == 'yb' ~ as.integer(str_split(Annotation, "_", simplify = TRUE)[, 1]),
        TRUE ~ NA_integer_
      ),
      End = case_when(
        IonType == 'b' ~ as.integer(str_sub(Annotation, 2)),
        IonType == 'y' ~ protein_length,
        IonType == 'yb' ~ as.integer(str_split(Annotation, "_", simplify = TRUE)[, 2]),
        TRUE ~ NA_integer_
      )
    ) %>%
    mutate(Height = End - Start + 1) %>% #Height == Length
    
  return(input_df)
}


seq_vec <- sequence_vector(fastafile)

control.df <- read_df (control_file, req_col)
fmt_ctrl.df <-
  add_column2df(control.df, ctrl_name, length(seq_vec))#Issues warnings, ignore
fmt_ctrl.df$ExptName <- NULL


exp.df <- read_df(experimental_file, req_col)
fmt_exp.df <-
  add_column2df(exp.df, treat_name, length(seq_vec))#Issues warnings, ignore
fmt_exp.df$ExptName <- NULL


# Combine the two experimental datasets
# Rename RelativeIntensity columns
ctrl <- fmt_ctrl.df %>% rename(RelativeIntensity_ctrl = RelativeIntensity)
oxdn <- fmt_exp.df %>% rename(RelativeIntensity_oxdn = RelativeIntensity)
combined_df <- full_join(ctrl %>% select(IonType, Annotation, VariableMod, FixedMod, RelativeIntensity_ctrl),
                         oxdn %>% select(IonType, Annotation, VariableMod, FixedMod, RelativeIntensity_oxdn),
                         by = c("IonType","Annotation", "VariableMod", "FixedMod"))
imputation_value = 0.01

combined_df$RelativeIntensity_ctrl[is.na(combined_df$RelativeIntensity_ctrl)] <- imputation_value
combined_df$RelativeIntensity_oxdn[is.na(combined_df$RelativeIntensity_oxdn)] <- imputation_value
combined_df <- add_termpos2df(combined_df, length(seq_vec))

# Sort b, yb and y ions in order and combine 

b_df <- combined_df %>% 
	filter(IonType == 'b') %>%
	arrange(Start, desc(Height))

f_df <- combined_df %>% 
	filter(IonType == 'yb') %>%
	arrange(Start, desc(Height))

y_df <- combined_df %>% 
	filter(IonType == 'y') %>%
	arrange(Start, desc(Height))	
	
allion_df <- bind_rows(b_df, f_df, y_df)	
allion_df <- allion_df %>%
  mutate(hue = case_when(
    RelativeIntensity_ctrl > RelativeIntensity_oxdn ~ "dodgerblue1",
    RelativeIntensity_ctrl < RelativeIntensity_oxdn  ~ "firebrick1",
    RelativeIntensity_ctrl == RelativeIntensity_oxdn  ~ "gray57",
    TRUE ~ NA_character_
  ),
  log_ratio = log2(RelativeIntensity_oxdn/ RelativeIntensity_ctrl)
  )

####################### Plot < or == or logic plot #######################################
# Plot/ PNG Params
lineWidth <- 2.8
opacity <- 0.9
opacity_commoncol = 0.9
opacity_col = 0.9
xcounter = 1
off_set <- 1 # correction for adjusting height
maxlen <- length(seq_vec)
xMax <-
  nrow(allion_df) # use to set the x-axis right end,consider common entries, adjust later if too much white space at right

png(
  file = "RelAbdLogicComp.A4V_25V_1134_CtrlOxdn.png",
  width = 12,
  height = 12,
  units = "in",
  res = 450,
  bg = "gray90"
)
par(font.axis = 2)#bold tick label
plot(
  0,
  type = "n",
  xlab = "Frag Ions",
  ylab = "Position",
  xlim = c(1, xMax + 2),
  ylim = c(1, maxlen),
  xaxs = "i",
  yaxs = "i",
  yaxt = "n"
  
)
xcounter <- 1
segments(
  x0 = xcounter,
  y0 = 1,
  x1 = xcounter,
  y1 = maxlen,
  col = alpha("white", 0.0),
  lwd = lineWidth,
  lend = 'butt'
) # vertical spacer at left

for (i in 1:nrow(allion.df)) {
  xcounter <- xcounter + 1
  begin = allion_df$Start[i]
  long  = allion_df$Height[i]
  ytop = maxlen - (begin - 1)
  ybot = ytop - long + off_set
  segcolor = allion_df$hue[i]
  #segcolor = allion.df$Color_viridis[i]
  
  segments(
    xcounter,
    ytop,
    xcounter,
    ybot,
    col = alpha(segcolor, opacity_col),
    lwd = lineWidth,
    lend = 'butt'
  )
  #segments(df$Start[i], df$Nindex[i], df$End[i], df$Nindex[i], col = df$Space[i], lwd = 2)
  
}

xcounter <- xcounter + 1
segments(
  x0 = xcounter,
  y0 = 1,
  x1 = xcounter,
  y1 = maxlen,
  col = alpha("white", 0.0),
  lwd = lineWidth,
  lend = 'butt'
) # vertical spacer at left
seq_serial <- paste0("  ", (1:maxlen))
seq_serial <- paste0(seq_vec, seq_serial)

axis(
  2,
  at = seq(maxlen, 1,-1),
  labels = seq_serial,
  cex.axis = 0.2,
  las = 2
)
#axis(2, at = seq(maxlen, 1, -1), labels = seqVec,cex.axis=0.2, las=2)#standard amino acid at left
axis(
  4,
  at = seq(maxlen, 1,-1),
  labels = seq_serial,
  cex.axis = 0.2,
  las = 2
)
#axis(4, at = seq(maxlen, 1, -1), labels = seqVec,cex.axis=0.2, las=2)#standard dual amino acid
##axis(4, at = seq(maxlen, 1, -1), labels = (1:maxlen),cex.axis=0.2, las=2, tcl=0.3)doesnt work


dev.off()
############################## DONE Logical map PLOTTING  ##################################

## Plot log-ratio
max_logratio <- max(allion_df$log_ratio, na.rm = TRUE)
min_logratio <- min(allion_df$log_ratio, na.rm = TRUE)
grad_name <- "RdBu"
#grad_name <- "RdYlBu"
#grad_name <- "YlOrRd"
num_colors <- 11 
palette <- colorRampPalette(rev(brewer.pal(n=num_colors, name=grad_name)))
num_bins <- num_colors #  same as num_colors or different
allion_df$bins <- cut(allion_df$log_ratio, breaks=num_bins, labels=FALSE)
allion_df$ratio_color <- palette(num_bins)[allion_df$bins]
# OR
allion_df$ratio_color <- colorRampPalette(rev(brewer.pal(n=11,name = grad_name)))(length(unique(allion_df$log_ratio)))[
 as.numeric(cut(allion_df$log_ratio, breaks = length(unique(allion_df$log_ratio))))
]
# OR
map_colors <- function(x, palette_name="RdBu", n=11, mid_color="lightblue") {
  # Generate the color palette
  pal <- colorRampPalette(c(brewer.pal(n, palette_name)[1:(n%/%2)], mid_color, brewer.pal(n, palette_name)[((n%/%2)+2):n]))(n + 1)
  
  # Bin x values directly without scaling
  bins <- cut(x, breaks = n, include.lowest = TRUE, labels = FALSE)
  
  # Apply the palette
  colors <- pal[bins]
  return(colors)
}

#allion_df$ratio_color <- map_colors(allion_df$log_ratio, mid_color="skyblue")
allion_df$ratio_color <- map_colors(allion_df$log_ratio, mid_color="bisque")


# Plot/ PNG Params
lineWidth <- 2.8
opacity <- 0.9
opacity_commoncol = 0.9
opacity_col = 0.9
xcounter = 1
off_set <- 1 # correction for adjusting height
maxlen <- length(seq_vec)
xMax <-
  nrow(allion_df) # use to set the x-axis right end,consider common entries, adjust later if too much white space at right

png(
  file = "Mapfunc.LogRatioPlot.FP1_A4V_25V_1134_CtrlOxdn_comparisonPlot.png",
  width = 12,
  height = 12,
  units = "in",
  res = 450
  #bg = ""
)
par(font.axis = 2)#bold tick label
plot(
  0,
  type = "n",
  xlab = "Frag Ions",
  ylab = "Position",
  xlim = c(1, xMax + 2),
  ylim = c(1, maxlen),
  xaxs = "i",
  yaxs = "i",
  yaxt = "n"
  
)
xcounter <- 1
segments(
  x0 = xcounter,
  y0 = 1,
  x1 = xcounter,
  y1 = maxlen,
  col = alpha("white", 0.0),
  lwd = lineWidth,
  lend = 'butt'
) # vertical spacer at left

for (i in 1:nrow(allion_df)) {
  xcounter <- xcounter + 1
  begin = allion_df$Start[i]
  long  = allion_df$Height[i]
  ytop = maxlen - (begin - 1)
  ybot = ytop - long + off_set
  segcolor = allion_df$ratio_color[i]
  #segcolor = frag.df$Color_viridis[i]
  
  segments(
    xcounter,
    ytop,
    xcounter,
    ybot,
    col = alpha(segcolor, opacity_col),
    lwd = lineWidth,
    lend = 'butt'
  )
  #segments(df$Start[i], df$Nindex[i], df$End[i], df$Nindex[i], col = df$Space[i], lwd = 2)
  
}
xcounter <- xcounter + 1
segments(
  x0 = xcounter,
  y0 = 1,
  x1 = xcounter,
  y1 = maxlen,
  col = alpha("white", 0.0),
  lwd = lineWidth,
  lend = 'butt'
) # vertical spacer at left
seq_serial <- paste0("  ", (1:maxlen))
seq_serial <- paste0(seq_vec, seq_serial)

axis(
  2,
  at = seq(maxlen, 1,-1),
  labels = seq_serial,
  cex.axis = 0.2,
  las = 2
)
#axis(2, at = seq(maxlen, 1, -1), labels = seqVec,cex.axis=0.2, las=2)#standard amino acid at left
axis(
  4,
  at = seq(maxlen, 1,-1),
  labels = seq_serial,
  cex.axis = 0.2,
  las = 2
)
#axis(4, at = seq(maxlen, 1, -1), labels = seqVec,cex.axis=0.2, las=2)#standard dual amino acid
##axis(4, at = seq(maxlen, 1, -1), labels = (1:maxlen),cex.axis=0.2, las=2, tcl=0.3)doesnt work


dev.off()

#plot Color-bar
# Assume x values are in a suitable range for direct mapping
map_barcolors <- function(x, palette_name="RdBu", n=11, mid_color="skyblue") {
  # Generate the color palette
  pal <- colorRampPalette(c(brewer.pal(n, palette_name)[1:(n%/%2)], mid_color, brewer.pal(n, palette_name)[((n%/%2)+2):n]))
  colors <- pal(n+1)
  # Direct mapping of x to colors without scaling
  color_indices = cut(x, breaks = n, labels = FALSE, include.lowest = TRUE)
  return(colors[color_indices])
}

# Generate the color bar
n <- 901 # Adjust based on your preference for color resolution
vals <- seq(min_logratio, max_logratio, length.out = n) # Direct range of x values
colors <- map_barcolors(vals, mid_color="bisque")

# Plot the color bar
plot(1, type="n", xlim=c(0,1), ylim=c(min(vals), max(vals)), xaxt="n", yaxt="n", xlab="", ylab="", bty="n")
for (i in 1:(n-1)) {
  rect(0, vals[i], 1, vals[i+1], col=colors[i], border=NA)
}

axis(4, at=seq(floor(min(vals)), ceiling(max(vals)), by=1), las=2)
mtext("Log Ratio", side=4, line=2.5)




# make a heatmap of (log2) relative abundances
# Give non-duplicate names to "Annotaion" if there are any

allion_df <- as.data.frame(allion_df %>%
  group_by(Annotation) %>%
  mutate(UniqueAnnotation = ifelse(n() > 1, paste(Annotation, row_number(), sep = "-"), Annotation)) %>%
  ungroup()
)

# View the modified data frame
head(allion_df)


data.mat <- allion_df %>% 
				select(RelativeIntensity_ctrl,RelativeIntensity_oxdn)
				
data.mat$RelativeIntensity_ctrl <- rev(data.mat$RelativeIntensity_ctrl)
data.mat$RelativeIntensity_oxdn <- rev(data.mat$RelativeIntensity_oxdn)
rownames(data.mat) = rev(allion_df$UniqueAnnotation)
data.mat <- as.matrix(data.mat)
data.mat <- log2(data.mat)

#color_palette <- colorRampPalette(rev(brewer.pal(n=11,name = "RdBu")))(100)
color_palette <- colorRampPalette(rev(brewer.pal(n=11,name = "RdBu")))(length(unique(c(data.mat))))
#my_qualitative <- sequential_hcl(100, palette = "Red-Blue") #bad

ann_df <- data.frame(Ion=rownames(data.mat))
rownames(ann_df) <- rownames(data.mat)
png("RevCtrlOxdn_pheatmapBuRdCol.png", width = 1000,height = 10000, res = 300)
pheatmap(data.mat,
		color = color_palette,
		#color = my_qualitative,
		#border_color = "grey55",
		border_color = "grey40",
		cluster_rows = FALSE,
		cluster_cols = FALSE,
		#annotation_row = ann_df,
		cellwidth = 30,
		cellheight = 10
)

dev.off()



stop()

# Create the heatmap
pheatmap(data_matrix, 
         main = "Heatmap with Row Labels on Left",
         show_rownames = FALSE)  # Hide default row names

# Add custom grid text for row labels
grid.text(row_label_pos, rownames(data_matrix), 
          rot = 90, vjust = 0.5, 
          gp = gpar(fontsize = 10))
